#![allow(dead_code)]

use anyhow::Result;

use crate::report::build::daily::{BuildContext, DataFreshnessSummary};

const METHODOLOGY_BODY: &str = "\
This report is produced by **pftui**, an open-source multi-timeframe analytics engine.

**Architecture:** Four specialist AI agents independently analyse markets at different time horizons: LOW (hours to days: price action, technicals, breaking news), MEDIUM (weeks to months: economic cycles, policy shifts, scenario management), HIGH (months to years: structural trends, technology disruption, commodity supercycles), and MACRO (years to decades: empire cycles, reserve currency transitions, power structure shifts). A cross-timeframe synthesis layer reconciles their outputs, surfacing both consensus and disagreement. The disagreements are often the most valuable signal.

**Data:** 19+ sources are aggregated into the pftui data store. Prices, technicals (RSI, SMA, MACD computed natively in Rust), COT positioning, COMEX vault inventory, FRED economic data, CME FedWatch probabilities, on-chain metrics, ETF flows, news feeds, economic calendar, and prediction market data can all feed the public report. One refresh command pulls the core data path.

**First Principles:**
- Follow the money, not the narrative. Track what institutions do, not what they say.
- Public statements from governments and institutions are tactical, not informational.
- Every divergence between rhetoric and capital flows is an intelligence signal.
- Predictions must be falsifiable, time-bound, and scored honestly.
- The system learns from its mistakes. Past prediction accuracy informs future confidence.

**Accountability:** Every prediction is logged, scored, and reviewed. Per-layer strict hit rate is published with scored sample size and uncertainty where available; layers with too few scored predictions are marked as low sample. Wrong calls are analysed for what was missed, and the lessons feed back into the analytical framework.

Learn more and explore the codebase: [pftui.com](https://pftui.com)";

const DISCLAIMER_FOOTER: &str = "\
---

*PFTUI Intelligence Report | pftui.dev*
*This report is for informational purposes only and does not constitute financial advice.*
*Generated by pftui Multi-Timeframe Analytics Engine*";

pub fn render_public_methodology(ctx: &BuildContext) -> Result<String> {
    let mut output = String::from("## Methodology\n\n");
    output.push_str(&render_runtime_metadata(ctx));
    output.push_str("\n\n");
    output.push_str(METHODOLOGY_BODY);
    if let Some(acc) = ctx.recommendation_accuracy_7d.as_ref() {
        output.push_str("\n\n");
        output.push_str(&format!(
            "**Recent recommendation accuracy ({}-day rolling):** hit rate {:.1}% across {} scored outcome(s) (avg score {:+.1} / 100). Recommendations are the imperative ADD / TRIM / HOLD calls the private report emits; outcomes are computed deterministically from price action since the recommendation date.",
            acc.window_days, acc.hit_rate_pct, acc.scored, acc.avg_score
        ));
    }
    output.push_str("\n\n");
    output.push_str(DISCLAIMER_FOOTER);

    Ok(output.trim_end().to_string())
}

fn render_runtime_metadata(ctx: &BuildContext) -> String {
    let mut output = format!(
        "**Report Date:** {}\n\n",
        ctx.report_date.as_deref().unwrap_or("unavailable")
    );
    output.push_str("**Data Freshness:**\n\n");
    output.push_str(&render_freshness_table(&ctx.data_freshness));
    output
}

fn render_freshness_table(rows: &[DataFreshnessSummary]) -> String {
    if rows.is_empty() {
        return "No structured freshness summary is attached to this build. Treat missing source rows as unavailable rather than fresh.".to_string();
    }

    let mut output =
        String::from("| Source | Last Fetch | Records | Status |\n|---|---|---:|---|\n");
    for row in rows {
        output.push_str(&format!(
            "| {} | {} | {} | {} |\n",
            clean_cell(&row.source),
            clean_cell(row.last_fetch.as_deref().unwrap_or("unknown")),
            row.records
                .map(|records| records.to_string())
                .unwrap_or_else(|| "n/a".to_string()),
            clean_cell(&row.status),
        ));
    }
    output.trim_end().to_string()
}

fn clean_cell(value: &str) -> String {
    value.replace('|', "/").trim().to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::report::build::daily::RecommendationAccuracySummary;

    #[test]
    fn public_methodology_includes_recommendation_accuracy_when_present() {
        let ctx = BuildContext {
            report_date: Some("2026-06-01".to_string()),
            recommendation_accuracy_7d: Some(RecommendationAccuracySummary {
                window_days: 7,
                scored: 4,
                hits: 3,
                hit_rate_pct: 75.0,
                avg_score: 32.5,
            }),
            ..BuildContext::default()
        };
        let rendered = render_public_methodology(&ctx).unwrap();
        assert!(rendered.contains("Recent recommendation accuracy"));
        assert!(rendered.contains("75.0%"));
        assert!(rendered.contains("4 scored outcome"));
    }

    #[test]
    fn public_methodology_omits_recommendation_accuracy_when_absent() {
        let ctx = BuildContext::default();
        let rendered = render_public_methodology(&ctx).unwrap();
        assert!(!rendered.contains("Recent recommendation accuracy"));
    }


    #[test]
    fn public_methodology_golden_output_is_stable_for_sparse_context() {
        let rendered = render_public_methodology(&BuildContext::default()).unwrap();
        let expected = "\
## Methodology

**Report Date:** unavailable

**Data Freshness:**

No structured freshness summary is attached to this build. Treat missing source rows as unavailable rather than fresh.

This report is produced by **pftui**, an open-source multi-timeframe analytics engine.

**Architecture:** Four specialist AI agents independently analyse markets at different time horizons: LOW (hours to days: price action, technicals, breaking news), MEDIUM (weeks to months: economic cycles, policy shifts, scenario management), HIGH (months to years: structural trends, technology disruption, commodity supercycles), and MACRO (years to decades: empire cycles, reserve currency transitions, power structure shifts). A cross-timeframe synthesis layer reconciles their outputs, surfacing both consensus and disagreement. The disagreements are often the most valuable signal.

**Data:** 19+ sources are aggregated into the pftui data store. Prices, technicals (RSI, SMA, MACD computed natively in Rust), COT positioning, COMEX vault inventory, FRED economic data, CME FedWatch probabilities, on-chain metrics, ETF flows, news feeds, economic calendar, and prediction market data can all feed the public report. One refresh command pulls the core data path.

**First Principles:**
- Follow the money, not the narrative. Track what institutions do, not what they say.
- Public statements from governments and institutions are tactical, not informational.
- Every divergence between rhetoric and capital flows is an intelligence signal.
- Predictions must be falsifiable, time-bound, and scored honestly.
- The system learns from its mistakes. Past prediction accuracy informs future confidence.

**Accountability:** Every prediction is logged, scored, and reviewed. Per-layer strict hit rate is published with scored sample size and uncertainty where available; layers with too few scored predictions are marked as low sample. Wrong calls are analysed for what was missed, and the lessons feed back into the analytical framework.

Learn more and explore the codebase: [pftui.com](https://pftui.com)

---

*PFTUI Intelligence Report | pftui.dev*
*This report is for informational purposes only and does not constitute financial advice.*
*Generated by pftui Multi-Timeframe Analytics Engine*";

        assert_eq!(rendered, expected);
        assert_public_safe(&rendered);
    }

    #[test]
    fn public_methodology_includes_disclaimer_footer() {
        let rendered = render_public_methodology(&BuildContext::default()).unwrap();

        assert!(rendered.contains("*PFTUI Intelligence Report | pftui.dev*"));
        assert!(rendered.contains(
            "*This report is for informational purposes only and does not constitute financial advice.*"
        ));
        assert!(rendered.contains("*Generated by pftui Multi-Timeframe Analytics Engine*"));
        assert_public_safe(&rendered);
    }

    #[test]
    fn public_methodology_renders_runtime_metadata_and_freshness() {
        let ctx = BuildContext {
            report_date: Some("2026-06-01".to_string()),
            data_freshness: vec![
                freshness("prices", Some("2026-06-01T08:15:00Z"), Some(240), "fresh"),
                freshness("news", None, None, "unavailable"),
            ],
            ..BuildContext::default()
        };

        let rendered = render_public_methodology(&ctx).unwrap();

        assert!(rendered.contains("**Report Date:** 2026-06-01"));
        assert!(rendered.contains("| prices | 2026-06-01T08:15:00Z | 240 | fresh |"));
        assert!(rendered.contains("| news | unknown | n/a | unavailable |"));
        assert_public_safe(&rendered);
    }

    fn freshness(
        source: &str,
        last_fetch: Option<&str>,
        records: Option<u64>,
        status: &str,
    ) -> DataFreshnessSummary {
        DataFreshnessSummary {
            source: source.to_string(),
            last_fetch: last_fetch.map(ToString::to_string),
            records,
            status: status.to_string(),
        }
    }

    fn assert_public_safe(markdown: &str) {
        let lowered = markdown.to_ascii_lowercase();
        for forbidden in [
            "skylar",
            "i hold",
            "we own",
            "our position",
            "my position",
            "cost basis",
            "unrealized",
            "transaction",
            "current allocation",
            "position size",
            "aapl",
            "tsla",
        ] {
            assert!(
                !lowered.contains(forbidden),
                "public methodology leaked private phrase {forbidden}: {markdown}"
            );
        }
    }
}
